# shellcheck shell=bash

load_runtime_context() {
  local default_profile

  read_manifest_contract

  ENGINE="${MANIFEST_ENGINE:-official}"
  default_profile="$(default_primary_profile_for_engine "${ENGINE}")"

  PUBLIC_DOMAIN="${MANIFEST_PUBLIC_DOMAIN:-}"
  PUBLIC_PORT="${MANIFEST_PUBLIC_PORT:-443}"
  INTERNAL_PORT="${MANIFEST_INTERNAL_PORT:-8888}"
  WORKERS="${MANIFEST_WORKERS:-1}"
  PRIMARY_PROFILE="${MANIFEST_PRIMARY_PROFILE:-${default_profile}}"
  LINK_STRATEGY="${MANIFEST_LINK_STRATEGY:-bundle}"
  DEVICE_NAMES="${MANIFEST_DEVICE_NAMES:-}"
  TLS_DOMAIN="${MANIFEST_TLS_DOMAIN:-${PUBLIC_DOMAIN}}"
  DECOY_MODE="${MANIFEST_DECOY_MODE:-disabled}"
  DECOY_TARGET_HOST="${MANIFEST_DECOY_TARGET_HOST:-}"
  DECOY_TARGET_PORT="${MANIFEST_DECOY_TARGET_PORT:-443}"
  DECOY_DOMAIN="${MANIFEST_DECOY_DOMAIN:-${TLS_DOMAIN}}"
  DECOY_LOCAL_PORT="${MANIFEST_DECOY_LOCAL_PORT:-10443}"
  DECOY_CERT_SOURCE_PATH="${MANIFEST_DECOY_CERT_SOURCE_PATH:-}"
  DECOY_KEY_SOURCE_PATH="${MANIFEST_DECOY_KEY_SOURCE_PATH:-}"

  OFFICIAL_REPO_URL="${MANIFEST_OFFICIAL_REPO_URL:-${OFFICIAL_REPO_URL_DEFAULT}}"
  OFFICIAL_REPO_BRANCH="${MANIFEST_OFFICIAL_REPO_BRANCH:-${OFFICIAL_REPO_BRANCH_DEFAULT}}"
  STEALTH_REPO_URL="${MANIFEST_STEALTH_REPO_URL:-${STEALTH_REPO_URL_DEFAULT}}"
  STEALTH_REPO_BRANCH="${MANIFEST_STEALTH_REPO_BRANCH:-${STEALTH_REPO_BRANCH_DEFAULT}}"

  DEVICE_NAMES="$(normalize_device_names_csv "${DEVICE_NAMES}")"
  PUBLIC_DOMAIN="${PUBLIC_DOMAIN,,}"
  TLS_DOMAIN="${TLS_DOMAIN,,}"
  DECOY_DOMAIN="${DECOY_DOMAIN,,}"

  validate_runtime_settings
}
