# shellcheck shell=bash

clear_requested_contract() {
  REQUESTED_OFFICIAL_REPO_URL=""
  REQUESTED_OFFICIAL_REPO_BRANCH=""
  REQUESTED_STEALTH_REPO_URL=""
  REQUESTED_STEALTH_REPO_BRANCH=""
  REQUESTED_PUBLIC_DOMAIN=""
  REQUESTED_PUBLIC_PORT=""
  REQUESTED_INTERNAL_PORT=""
  REQUESTED_WORKERS=""
  REQUESTED_ENGINE=""
  REQUESTED_PRIMARY_PROFILE=""
  REQUESTED_LINK_STRATEGY=""
  REQUESTED_DEVICE_NAMES=""
  REQUESTED_TLS_DOMAIN=""
  REQUESTED_DECOY_MODE=""
  REQUESTED_DECOY_TARGET_HOST=""
  REQUESTED_DECOY_TARGET_PORT=""
  REQUESTED_DECOY_DOMAIN=""
  REQUESTED_DECOY_LOCAL_PORT=""
  REQUESTED_DECOY_CERT_PATH=""
  REQUESTED_DECOY_KEY_PATH=""
}

read_requested_contract() {
  clear_requested_contract

  REQUESTED_OFFICIAL_REPO_URL="${OFFICIAL_REPO_URL:-${REPO_URL:-}}"
  REQUESTED_OFFICIAL_REPO_BRANCH="${OFFICIAL_REPO_BRANCH:-${REPO_BRANCH:-}}"
  REQUESTED_STEALTH_REPO_URL="${STEALTH_REPO_URL:-}"
  REQUESTED_STEALTH_REPO_BRANCH="${STEALTH_REPO_BRANCH:-}"

  REQUESTED_PUBLIC_DOMAIN="${PUBLIC_DOMAIN:-}"
  REQUESTED_PUBLIC_PORT="${PUBLIC_PORT:-${PORT:-}}"
  REQUESTED_INTERNAL_PORT="${INTERNAL_PORT:-}"
  REQUESTED_WORKERS="${WORKERS:-}"
  REQUESTED_ENGINE="${ENGINE:-}"
  REQUESTED_PRIMARY_PROFILE="${PRIMARY_PROFILE:-}"
  REQUESTED_LINK_STRATEGY="${LINK_STRATEGY:-}"
  REQUESTED_DEVICE_NAMES="${DEVICE_NAMES:-}"
  REQUESTED_TLS_DOMAIN="${TLS_DOMAIN:-}"
  REQUESTED_DECOY_MODE="${DECOY_MODE:-}"
  REQUESTED_DECOY_TARGET_HOST="${DECOY_TARGET_HOST:-}"
  REQUESTED_DECOY_TARGET_PORT="${DECOY_TARGET_PORT:-}"
  REQUESTED_DECOY_DOMAIN="${DECOY_DOMAIN:-}"
  REQUESTED_DECOY_LOCAL_PORT="${DECOY_LOCAL_PORT:-}"
  REQUESTED_DECOY_CERT_PATH="${DECOY_CERT_PATH:-}"
  REQUESTED_DECOY_KEY_PATH="${DECOY_KEY_PATH:-}"
}

requested_domain_inputs_present() {
  read_requested_contract
  [[ -n "${REQUESTED_PUBLIC_DOMAIN}" || -n "${REQUESTED_TLS_DOMAIN}" ]]
}
