# shellcheck shell=bash

read_requested_contract() {
  REQUESTED_PUBLIC_DOMAIN=""
  REQUESTED_PUBLIC_PORT=""
  REQUESTED_INTERNAL_PORT=""
  REQUESTED_WORKERS=""
  REQUESTED_ENGINE=""
  REQUESTED_PRIMARY_PROFILE=""
  REQUESTED_LINK_STRATEGY=""
  REQUESTED_DEVICE_NAMES=""
  REQUESTED_TLS_DOMAIN=""
  REQUESTED_DECOY_MODE=""
  REQUESTED_DECOY_TARGET_HOST=""
  REQUESTED_DECOY_TARGET_PORT=""
  REQUESTED_DECOY_DOMAIN=""
  REQUESTED_DECOY_LOCAL_PORT=""
  REQUESTED_DECOY_CERT_PATH=""
  REQUESTED_DECOY_KEY_PATH=""
  REQUESTED_OFFICIAL_REPO_URL=""
  REQUESTED_OFFICIAL_REPO_BRANCH=""
  REQUESTED_STEALTH_REPO_URL=""
  REQUESTED_STEALTH_REPO_BRANCH=""

  [[ -n "${PUBLIC_DOMAIN+set}" ]] && REQUESTED_PUBLIC_DOMAIN="${PUBLIC_DOMAIN}"

  if [[ -n "${PUBLIC_PORT+set}" ]]; then
    REQUESTED_PUBLIC_PORT="${PUBLIC_PORT}"
  elif [[ -n "${PORT+set}" ]]; then
    REQUESTED_PUBLIC_PORT="${PORT}"
  fi

  [[ -n "${INTERNAL_PORT+set}" ]] && REQUESTED_INTERNAL_PORT="${INTERNAL_PORT}"
  [[ -n "${WORKERS+set}" ]] && REQUESTED_WORKERS="${WORKERS}"
  [[ -n "${ENGINE+set}" ]] && REQUESTED_ENGINE="${ENGINE}"
  [[ -n "${PRIMARY_PROFILE+set}" ]] && REQUESTED_PRIMARY_PROFILE="${PRIMARY_PROFILE}"
  [[ -n "${LINK_STRATEGY+set}" ]] && REQUESTED_LINK_STRATEGY="${LINK_STRATEGY}"
  [[ -n "${DEVICE_NAMES+set}" ]] && REQUESTED_DEVICE_NAMES="${DEVICE_NAMES}"
  [[ -n "${TLS_DOMAIN+set}" ]] && REQUESTED_TLS_DOMAIN="${TLS_DOMAIN}"
  [[ -n "${DECOY_MODE+set}" ]] && REQUESTED_DECOY_MODE="${DECOY_MODE}"
  [[ -n "${DECOY_TARGET_HOST+set}" ]] && REQUESTED_DECOY_TARGET_HOST="${DECOY_TARGET_HOST}"
  [[ -n "${DECOY_TARGET_PORT+set}" ]] && REQUESTED_DECOY_TARGET_PORT="${DECOY_TARGET_PORT}"
  [[ -n "${DECOY_DOMAIN+set}" ]] && REQUESTED_DECOY_DOMAIN="${DECOY_DOMAIN}"
  [[ -n "${DECOY_LOCAL_PORT+set}" ]] && REQUESTED_DECOY_LOCAL_PORT="${DECOY_LOCAL_PORT}"
  [[ -n "${DECOY_CERT_PATH+set}" ]] && REQUESTED_DECOY_CERT_PATH="${DECOY_CERT_PATH}"
  [[ -n "${DECOY_KEY_PATH+set}" ]] && REQUESTED_DECOY_KEY_PATH="${DECOY_KEY_PATH}"
  [[ -n "${OFFICIAL_REPO_URL+set}" ]] && REQUESTED_OFFICIAL_REPO_URL="${OFFICIAL_REPO_URL}"
  [[ -n "${OFFICIAL_REPO_BRANCH+set}" ]] && REQUESTED_OFFICIAL_REPO_BRANCH="${OFFICIAL_REPO_BRANCH}"
  [[ -n "${STEALTH_REPO_URL+set}" ]] && REQUESTED_STEALTH_REPO_URL="${STEALTH_REPO_URL}"
  [[ -n "${STEALTH_REPO_BRANCH+set}" ]] && REQUESTED_STEALTH_REPO_BRANCH="${STEALTH_REPO_BRANCH}"
}
