# shellcheck shell=bash

stealth_build_engine_binary() {
  log "Собираю telemt..."
  cd "${STEALTH_SRC_DIR}"
  cargo build --release
  [[ -x "${STEALTH_SRC_DIR}/target/release/telemt" ]] || die "Бинарник telemt не собран"
  install -m 0755 "${STEALTH_SRC_DIR}/target/release/telemt" "${STEALTH_BIN_PATH}"
  setcap -r "${STEALTH_BIN_PATH}" 2>/dev/null || true
}

compute_link_mode_flags() {
  HAS_CLASSIC="false"
  HAS_SECURE="false"
  HAS_TLS="false"

  local name profile
  while IFS=$'\t' read -r name profile; do
    [[ -n "${name}" ]] || continue
    case "${profile}" in
      classic) HAS_CLASSIC="true" ;;
      dd) HAS_SECURE="true" ;;
      ee) HAS_TLS="true" ;;
      *) die "Неизвестный профиль в definitions: ${profile}" ;;
    esac
  done < "${LINK_DEFINITIONS_PATH}"
}

render_stealth_config() {
  local mask_enabled="false"
  local unknown_sni_action="reject_handshake"
  local name profile secret_file stored_secret raw_secret

  compute_link_mode_flags

  if [[ "${DECOY_MODE}" == "upstream-forward" || "${DECOY_MODE}" == "local-https" ]]; then
    mask_enabled="true"
    unknown_sni_action="mask"
  fi

  cat > "${STEALTH_CONFIG_PATH}" <<EOF_CFG
### Generated by ${APP_NAME}
[general]
use_middle_proxy = true
log_level = "normal"

[general.modes]
classic = ${HAS_CLASSIC}
secure = ${HAS_SECURE}
tls = ${HAS_TLS}

[general.links]
show = "*"
public_host = "${PUBLIC_DOMAIN}"
public_port = ${PUBLIC_PORT}

[server]
port = ${PUBLIC_PORT}

[server.api]
enabled = false
listen = "127.0.0.1:9091"
whitelist = ["127.0.0.1/32", "::1/128"]
minimal_runtime_enabled = false
minimal_runtime_cache_ttl_ms = 1000

[[server.listeners]]
ip = "0.0.0.0"

[censorship]
tls_domain = "${TLS_DOMAIN}"
mask = ${mask_enabled}
tls_emulation = true
tls_front_dir = "${STEALTH_TLS_FRONT_DIR}"
unknown_sni_action = "${unknown_sni_action}"
EOF_CFG

  if [[ "${DECOY_MODE}" == "upstream-forward" ]]; then
    cat >> "${STEALTH_CONFIG_PATH}" <<EOF_CFG
mask_host = "${DECOY_TARGET_HOST}"
mask_port = ${DECOY_TARGET_PORT}
EOF_CFG
  elif [[ "${DECOY_MODE}" == "local-https" ]]; then
    cat >> "${STEALTH_CONFIG_PATH}" <<EOF_CFG
mask_host = "127.0.0.1"
mask_port = ${DECOY_LOCAL_PORT}
EOF_CFG
  fi

  printf '\n[access.users]\n' >> "${STEALTH_CONFIG_PATH}"
  while IFS=$'\t' read -r name profile; do
    [[ -n "${name}" ]] || continue
    secret_file="$(secret_file_for_name "${name}")"
    stored_secret="$(normalize_secret "${secret_file}")"
    raw_secret="$(extract_raw_secret_hex "${stored_secret}")"
    printf '%s = "%s"\n' "${name}" "${raw_secret}" >> "${STEALTH_CONFIG_PATH}"
  done < "${LINK_DEFINITIONS_PATH}"
}

stealth_render_runtime_artifacts() {
  render_stealth_config
}

stealth_runtime_artifacts_present() {
  [[ -f "${STEALTH_CONFIG_PATH}" && -x "${STEALTH_BIN_PATH}" ]]
}
